# Generated by Django 3.2.7 on 2021-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blog_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='blog count'),
        ),
    ]
