# Generated by Django 3.2.7 on 2021-10-30 13:43

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
