export const GET_SEARCH_ACCOUNTS_SUCCESS = 'GET_SEARCH_ACCOUNTS_SUCCESS';
export const GET_SEARCH_ACCOUNTS_FAIL = 'GET_SEARCH_ACCOUNTS_FAIL';
export const GET_SEARCH_ACCOUNTS_NEXT_SUCCESS = 'GET_SEARCH_ACCOUNTS_NEXT_SUCCESS';
export const GET_SEARCH_ACCOUNTS_NEXT_FAIL = 'GET_SEARCH_ACCOUNTS_NEXT_FAIL';

export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAIL = 'GET_ACCOUNT_FAIL';


export const GET_ACCOUNT_BLOGS_SUCCESS = 'GET_ACCOUNT_BLOGS_SUCCESS';
export const GET_ACCOUNT_BLOGS_FAIL = 'GET_ACCOUNT_BLOGS_FAIL';
export const GET_ACCOUNT_BLOGS_NEXT_SUCCESS = 'GET_ACCOUNT_BLOGS_NEXT_SUCCESS';
export const GET_ACCOUNT_BLOGS_NEXT_FAIL = 'GET_ACCOUNT_BLOGS_NEXT_FAIL';

export const GET_ACCOUNT_FOLLOWERS_SUCCESS = 'GET_ACCOUNT_FOLLOWERS_SUCCESS';
export const GET_ACCOUNT_FOLLOWERS_FAIL = 'GET_ACCOUNT_FOLLOWERS_FAIL';
export const GET_ACCOUNT_FOLLOWERS_NEXT_SUCCESS = 'GET_ACCOUNT_FOLLOWERS_NEXT_SUCCESS';
export const GET_ACCOUNT_FOLLOWERS_NEXT_FAIL = 'GET_ACCOUNT_FOLLOWERS_NEXT_FAIL';