export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_FAIL = 'ACTIVATE_FAIL';

export const LOGOUT = 'LOGOUT';

export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';

export const CHANGE_USER_DATA_SUCCESS = 'CHANGE_USER_DATA_SUCCESS';
export const CHANGE_USER_DATA_FAIL = 'CHANGE_USER_DATA_FAIL';

export const GET_USER_FOLLOWERS_SUCCESS = 'GET_USER_FOLLOWERS_SUCCESS';
export const GET_USER_FOLLOWERS_FAIL = 'GET_USER_FOLLOWERS_FAIL';
export const GET_USER_FOLLOWERS_NEXT_SUCCESS = 'GET_USER_FOLLOWERS_NEXT_SUCCESS';
export const GET_USER_FOLLOWERS_NEXT_FAIL = 'GET_USER_FOLLOWERS_NEXT_FAIL';

export const GET_USER_BLOGS_SUCCESS = 'GET_USER_BLOGS_SUCCESS';
export const GET_USER_BLOGS_FAIL = 'GET_USER_BLOGS_FAIL';
export const GET_USER_BLOGS_NEXT_SUCCESS = 'GET_USER_BLOGS_NEXT_SUCCESS';
export const GET_USER_BLOGS_NEXT_FAIL = 'GET_USER_BLOGS_NEXT_FAIL';