export const GET_SEARCH_BLOGS_SUCCESS = 'GET_SEARCH_BLOGS_SUCCESS';
export const GET_SEARCH_BLOGS_FAIL = 'GET_SEARCH_BLOGS_FAIL';
export const GET_SEARCH_BLOGS_NEXT_SUCCESS = 'GET_SEARCH_BLOGS_NEXT_SUCCESS';
export const GET_SEARCH_BLOGS_NEXT_FAIL = 'GET_SEARCH_BLOGS_NEXT_FAIL';

export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';
export const GET_BLOG_COMMENTS_SUCCESS = 'GET_BLOG_COMMENTS_SUCCESS';
export const GET_BLOG_COMMENTS_FAIL = 'GET_BLOG_COMMENTS_FAIL';
export const GET_BLOG_COMMENTS_NEXT_SUCCESS = 'GET_BLOG_COMMENTS_NEXT_SUCCESS';
export const GET_BLOG_COMMENTS_NEXT_FAIL = 'GET_BLOG_COMMENTS_NEXT_FAIL';

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';