export const GET_SEARCH_BLOGS_SUCCESS = 'GET_SEARCH_BLOGS_SUCCESS';
export const GET_SEARCH_BLOGS_FAIL = 'GET_SEARCH_BLOGS_FAIL';
export const GET_SEARCH_BLOGS_NEXT_SUCCESS = 'GET_SEARCH_BLOGS_NEXT_SUCCESS';
export const GET_SEARCH_BLOGS_NEXT_FAIL = 'GET_SEARCH_BLOGS_NEXT_FAIL';

export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';