export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAIL = 'GET_FEED_FAIL';
export const GET_FEED_NEXT_SUCCESS = 'GET_FEED_NEXT_SUCCESS';
export const GET_FEED_NEXT_FAIL = 'GET_FEED_NEXT_FAIL';